#Service Integration
ATTRACTIONS = "ATTRACTIONS"
F00D_BEVERAGE = "F&B"
BARS_CLUBS = "BARS and CLUBS"
#Parent Conversation Handler States
USING_SERVICE = "USING SERVICE"
CHOOSING_SERVICE = "CHOOSING SERVICE"

#Common Service
BACK = "BACK"
NEXT_PAGE = "NEXT PAGE"
PREV_PAGE = "PREV PAGE"
EXIT = "EXIT SERVICE"

#Attraction Service
GET_NEAREST_ATTRACTIONS = "GET NEAREST ATTRACTIONS"
SEARCH_ATTRACTION_DETAILS = "SEARCH ATTRACTION DETAILS"
SEARCH_ATTRACTIONS = "SEARCH ATTRACTIONS"
GET_ATTRACTION_REVIEWS = "GET ATTRACTION REVIEWS"

#FNB Service
GET_NEAREST_FNBS = "GET NEAREST FNBS"
SEARCH_FNB_DETAILS = "SEARCH FNB DETAILS"
SEARCH_FNBS = "SEARCH FNBS"
GET_FNB_REVIEWS = "GET FNB REVIEWS"

#Bars And Clubs Service
GET_NEAREST_BARS_CLUBS = "GET NEAREST BARS_CLUBS"
SEARCH_BAR_CLUB_DETAILS = "SEARCH BAR_CLUB DETAILS"
SEARCH_BARS_CLUBS = "SEARCH BARS_CLUBS"
GET_BAR_CLUB_REVIEWS = "GET BAR_CLUB REVIEWS"